POST https://localhost:7084/Auth/changepassword HTTP/1.1
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJiaGFhY2tAcGhhZW5vYmlvdGVjaC5jb20iLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6ImEyYTRhOTFkLTFjMTUtNDRkYi1hMDAxLTczYmQ0ZWE5OGYzMSIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IlBoYWVuby1BZG1pbiIsImV4cCI6MTczODIyNTcyMCwiaXNzIjoiQ29tcGx5IiwiYXVkIjoiY29tcGx5In0.bzJFBRFVIihW1GQ01vaACjZEMSRZ7wFsdOGzMfqC3UU50MvHN8xajjrPA4sTF0Im2EDkbBVtLXh3QaUXqT9lgw

{
    "currentPassword": "Password1!",
    "newPassword": "v2Hayek1!"
}
