import { ROLES } from "./auth.roles"

export const ROLE_GROUPS = {
  PHAENO: [ROLES.PHAENO_USER, ROLES.PHAENO_ADMIN],
  CUSTOMER: [ROLES.CUSTOMER_USER, ROLES.CUSTOMER_ADMIN],
  PARTNER: [ROLES.PARTNER_USER, ROLES.PARTNER_ADMIN],

  ADMINS: [
    ROLES.PHAENO_ADMIN,
    ROLES.CUSTOMER_ADMIN,
    ROLES.PARTNER_ADMIN,
  ],
} as const