import IMenuListItem from "../types/IMenuListItem";

export const userMenuList: IMenuListItem[] = [
  // {
  //   index: 0,
  //   isMain: true,
  //   type: 'link',
  //   subtype: 'home',
  //   label: 'Home',
  //   route: '/',
  //   userDataRoute: false,
  // },
  {
    index: 1,
    isMain: true,
    type: 'link',
    subtype: 'browser',
    label: 'Browser',
    route: '/app/browser',
    userDataRoute: true,
  },
  {
    index: 2,
    isMain: true,
    type: 'link',
    subtype: 'analytics',
    label: 'Analytics',
    route: '/app/analytics',
    userDataRoute: true,
  },  
  {
    index: 3,
    isMain: true,
    type: 'link',
    subtype: 'files',
    label: 'Files',
    route: '/app/files',
    userDataRoute: true,
  },
  {
    index: 4,
    isMain: false,
    type: 'button',
    subtype: 'api-keys',
    label: 'API Keys',
    route: 'none',
    userDataRoute: false,
  },
  {
    index: 5,
    isMain: false,
    type: 'link',
    subtype: 'customers',
    label: 'Customers',
    route: '/app/customers',
    userDataRoute: false,
  },  
  {
    index: 6,
    isMain: false,
    type: 'link',
    subtype: 'users',
    label: 'Users',
    route: '/app/users',
    userDataRoute: false,
  },
  {
    index: 7,
    isMain: false,
    type: 'button',
    subtype: 'security-settings',
    label: 'Security Settings',
    route: 'none',
    userDataRoute: false,
  },
  {
    index: 8,
    isMain: false,
    type: 'button',
    subtype: 'signout',
    label: 'Sign Out',
    route: 'none',
    userDataRoute: false,
  },
];