/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FilesIndexRouteImport } from './routes/files/index'
import { Route as BrowserIndexRouteImport } from './routes/browser/index'
import { Route as AuthIndexRouteImport } from './routes/auth/index'
import { Route as AnalyticsIndexRouteImport } from './routes/analytics/index'
import { Route as AuthTwoFactorRouteImport } from './routes/auth/two-factor'
import { Route as AuthSigninRouteImport } from './routes/auth/signin'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FilesIndexRoute = FilesIndexRouteImport.update({
  id: '/files/',
  path: '/files/',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowserIndexRoute = BrowserIndexRouteImport.update({
  id: '/browser/',
  path: '/browser/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/auth/',
  path: '/auth/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsIndexRoute = AnalyticsIndexRouteImport.update({
  id: '/analytics/',
  path: '/analytics/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthTwoFactorRoute = AuthTwoFactorRouteImport.update({
  id: '/auth/two-factor',
  path: '/auth/two-factor',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSigninRoute = AuthSigninRouteImport.update({
  id: '/auth/signin',
  path: '/auth/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/signin': typeof AuthSigninRoute
  '/auth/two-factor': typeof AuthTwoFactorRoute
  '/analytics': typeof AnalyticsIndexRoute
  '/auth': typeof AuthIndexRoute
  '/browser': typeof BrowserIndexRoute
  '/files': typeof FilesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/signin': typeof AuthSigninRoute
  '/auth/two-factor': typeof AuthTwoFactorRoute
  '/analytics': typeof AnalyticsIndexRoute
  '/auth': typeof AuthIndexRoute
  '/browser': typeof BrowserIndexRoute
  '/files': typeof FilesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/signin': typeof AuthSigninRoute
  '/auth/two-factor': typeof AuthTwoFactorRoute
  '/analytics/': typeof AnalyticsIndexRoute
  '/auth/': typeof AuthIndexRoute
  '/browser/': typeof BrowserIndexRoute
  '/files/': typeof FilesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth/forgot-password'
    | '/auth/signin'
    | '/auth/two-factor'
    | '/analytics'
    | '/auth'
    | '/browser'
    | '/files'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/forgot-password'
    | '/auth/signin'
    | '/auth/two-factor'
    | '/analytics'
    | '/auth'
    | '/browser'
    | '/files'
  id:
    | '__root__'
    | '/'
    | '/auth/forgot-password'
    | '/auth/signin'
    | '/auth/two-factor'
    | '/analytics/'
    | '/auth/'
    | '/browser/'
    | '/files/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthSigninRoute: typeof AuthSigninRoute
  AuthTwoFactorRoute: typeof AuthTwoFactorRoute
  AnalyticsIndexRoute: typeof AnalyticsIndexRoute
  AuthIndexRoute: typeof AuthIndexRoute
  BrowserIndexRoute: typeof BrowserIndexRoute
  FilesIndexRoute: typeof FilesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/files/': {
      id: '/files/'
      path: '/files'
      fullPath: '/files'
      preLoaderRoute: typeof FilesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browser/': {
      id: '/browser/'
      path: '/browser'
      fullPath: '/browser'
      preLoaderRoute: typeof BrowserIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics/': {
      id: '/analytics/'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/two-factor': {
      id: '/auth/two-factor'
      path: '/auth/two-factor'
      fullPath: '/auth/two-factor'
      preLoaderRoute: typeof AuthTwoFactorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signin': {
      id: '/auth/signin'
      path: '/auth/signin'
      fullPath: '/auth/signin'
      preLoaderRoute: typeof AuthSigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthSigninRoute: AuthSigninRoute,
  AuthTwoFactorRoute: AuthTwoFactorRoute,
  AnalyticsIndexRoute: AnalyticsIndexRoute,
  AuthIndexRoute: AuthIndexRoute,
  BrowserIndexRoute: BrowserIndexRoute,
  FilesIndexRoute: FilesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
